import 'package:google_fonts/google_fonts.dart';

///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Res {
  Res._();

  static String appFontFamily = GoogleFonts.cairo().fontFamily ?? '';

  //========================== Api Endpoints  ===============================
  static const apiLogin = 'auth/login';
  static const apiLogout = 'auth/logout';
  static const apiRequests = 'driver/request-drivers';
  static const apiAcceptRequest = 'driver/request-driver-accept';
  static const apiStartParking = 'driver/start-parking-car';
  static const apiEndParking = 'driver/end-parking-car';
  static const apiGetParkingList = 'driver/parked-cars/search';
  static const apiParkCar = 'driver/confirm-start-parking-car';

  //========================== Animation Assets  ===============================
  static const animApiLoading = 'assets/anim/api_loading.json';
  static const animApiEmpty = 'assets/anim/api_empty.json';
  static const animApiError = 'assets/anim/api_error.json';
  static const animDelivery = 'assets/anim/delivery.json';
  static const animEmptyCart = 'assets/anim/empty_cart.json';
  static const animSuccess = 'assets/anim/success.json';
  static const animDisconnect = 'assets/anim/disconnect.json';
  static const animClock = 'assets/anim/clock.json';

  //========================== Icons Assets  ===============================
  static const String iconName = 'assets/icons/name.svg';
  static const String iconEmail = 'assets/icons/email.svg';
  static const String iconPhone = 'assets/icons/phone.svg';
  static const String iconPassword = 'assets/icons/password.svg';
  static const String iconSuccess = 'assets/icons/success.svg';
  static const String iconError = 'assets/icons/error.svg';
  static const String iconLocation = 'assets/icons/location.svg';
  static const String iconPhoneVerified = 'assets/icons/phone_verified.svg';
  static const String iconForgetPassword = 'assets/icons/forget_password.svg';
  static const String iconParking = 'assets/icons/parking.svg';
  static const String iconValet = 'assets/icons/valet.svg';
  static const String iconServices = 'assets/icons/services.svg';
  static const String iconBooking = 'assets/icons/booking.svg';
  static const String iconMenu = 'assets/icons/menu.svg';
  static const String iconNewPassword = 'assets/icons/new_password.svg';
  static const String iconScan = 'assets/icons/scan.svg';
  static const String iconMale = 'assets/icons/male.svg';
  static const String iconFemale = 'assets/icons/female.svg';
  static const String iconEmptyUsers = 'assets/icons/empty_users.svg';
  static const String iconEmptyCars = 'assets/icons/empty_cars.svg';
  static const String iconEmptyServices = 'assets/icons/empty_services.svg';
  static const String iconGarageLocation = 'assets/icons/garage_location.svg';
  static const String iconStaff = 'assets/icons/staff.svg';
  static const String iconClock = 'assets/icons/clock.svg';
  static const String iconCamera = 'assets/icons/camera.svg';
  static const String iconBlueBorder = 'assets/icons/blue_border.svg';
  static const String iconRedBorder = 'assets/icons/red_border.svg';
  static const String iconEmptyRequests = 'assets/icons/empty_requests.svg';
  static const String iconQr = 'assets/icons/qr.svg';

  //========================== Images Assets  ===============================
  static const logoImage = "assets/images/launcher/logo.png";
  static const splashBgImage = "assets/images/splash_bg.png";
  static const locationPinImage = 'assets/images/my_pin.png';

}
