name: driver
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  fcm_config: ^3.5.3
  shimmer: ^3.0.0
  intl_phone_field: ^3.2.0
  vibration: ^1.8.4
  toggle_switch: ^2.1.0
  image_picker: ^1.0.5
  #  dart run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  lottie: ^2.7.0
  connectivity_plus: ^5.0.2
  pretty_dio_logger: ^1.3.1
  oktoast: ^3.4.0
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  qr_flutter: ^4.1.0
  package_info_plus: ^5.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  google_fonts: 6.1.0
  qr_code_scanner: ^1.0.1
  audioplayers: ^5.2.1
  grouped_list: ^5.1.2
  lazy_load_scrollview: ^1.3.0
  geolocator: ^10.1.1
  location: ^5.0.3
  permission_handler: ^11.1.0
  google_maps_flutter: ^2.5.1
  flutter_polyline_points: ^2.0.0



  #  check flutter_native_splash.yaml in root directory to change configurations
  #  dart run flutter_native_splash:create ==> to apply
  #  dart run flutter_native_splash:remove ==> to remove


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: assets/images/launcher/logo.png
  image_path_android: assets/images/launcher/logo.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/launcher/
    - assets/icons/
    - assets/anim/
    - assets/audio/